#include "accessory_protocol.h"

static_assert(KIDI_ACCESSORY_PROTOCOL_VERSION == 1U);
static_assert(KIDI_ACCESSORY_CONTROL_PORT >= 61440U);
static_assert(KIDI_ACCESSORY_MEDIA_PORT >= 49152U && KIDI_ACCESSORY_MEDIA_PORT < 61440U);
static_assert(KIDI_ACCESSORY_MEDIA_PHOTO != KIDI_ACCESSORY_MEDIA_AUDIO);
