[platformio]
default_envs = esp32s3_compile_check
src_dir = .

[env:esp32s3_compile_check]
platform = espressif32@6.12.0
board = esp32-s3-devkitc-1
framework = arduino
build_src_filter =
    -<*>
    +<src/*.cpp>
    +<tests/firmware/main.cpp>
board_build.arduino.memory_type = qio_opi
board_build.flash_mode = qio
build_unflags = -std=gnu++11
build_flags =
    -std=gnu++17
    -Wall
    -Wextra
    -Werror
    -Isrc
    -DBOARD_HAS_PSRAM
    -DARDUINO_USB_MODE=1
    -DARDUINO_USB_CDC_ON_BOOT=1
monitor_speed = 115200
