include_guard(GLOBAL)

function(kidi_add_test target source)
    add_executable(${target} "${source}")
    target_link_libraries(${target} PRIVATE kidi::kidi ${ARGN})
    add_test(NAME ${target} COMMAND ${target})
endfunction()

add_executable(kidi_argparse_test tests/kidi/cli/argparse_test.cpp)
target_link_libraries(kidi_argparse_test PRIVATE kidi::argparse)
add_test(NAME kidi_argparse_test COMMAND kidi_argparse_test)

kidi_add_test(kidi_manifest_test tests/kidi/model/config_test.cpp)
kidi_add_test(kidi_tokenizer_test tests/kidi/text/tokenizer_test.cpp ZLIB::ZLIB)
kidi_add_test(kidi_rtg_package_test tests/kidi/model/package_test.cpp)
kidi_add_test(kidi_gemma4_test tests/kidi/model/gemma4_test.cpp)
target_compile_definitions(kidi_gemma4_test PRIVATE KIDI_GEMMA4_FIXTURE="${PROJECT_SOURCE_DIR}/tests/data/gemma4")
kidi_add_test(kidi_decoder_test tests/kidi/inference/decoder_test.cpp)
kidi_add_test(kidi_weights_test tests/kidi/model/weights_test.cpp)
kidi_add_test(kidi_tensor_test tests/kidi/tensor/tensor_test.cpp)
kidi_add_test(kidi_eager_test tests/kidi/layers/eager_test.cpp)
kidi_add_test(kidi_ynnpack_weights_test tests/kidi/runtime/ynn/weights_test.cpp kidi::ynnpack)
kidi_add_test(kidi_ynn_runtime_test tests/kidi/runtime/ynn/graph_test.cpp)
kidi_add_test(kidi_rtg_embedding_test tests/kidi/layers/embedding_test.cpp)
kidi_add_test(kidi_rtg_transformer_builder_test tests/kidi/layers/transformer_test.cpp)
kidi_add_test(kidi_rtg_attention_test tests/kidi/layers/attention_test.cpp)
kidi_add_test(kidi_rtg_precision_test tests/kidi/layers/precision_test.cpp)
kidi_add_test(kidi_rtg_int8_precision_test tests/kidi/layers/int8_precision_test.cpp)
